### ISSUE TITLE
hercules-build makefile references old versions of docker stages

### ISSUE THREAD

**Issue by Buluphont** [fpiesche/docker-hercules#10]
As implied by issue title, the current version of `hercules-build/Makefile` attempts to assemble a Dockerfile using stages that no longer exist in the repo, probably due to a refactor.

**Comment by fpiesche** [comment]
Yeah - I had started, and failed to finish or merge properly, a rework of how the builds work. This was partly because GitHub's CI system was failing to finish builds and ran out of memory (!), partly because I couldn't get Woodpecker CI set up on my own hardware because of its then-unfinished ARM support and partly because life and day job stuff ended up clogging my brainspace.

I've now sorted the builds and we have CI going to Docker images again! ARMv6 (Raspberry Pi 1, original Pi Zero) is untested, though - I don't have a Pi1 running to test on anymore, and the multi-arch builds actually use Debian's `linux/arm/v7` base image but with armv6-only hardware features as there is no `v6` image for either Debian or Ubuntu.
